### ISSUE TITLE
`htmlToAnnotatedString` crashes randomly with `java.lang.IndexOutOfBoundsException` on version 1.0.1

### ISSUE THREAD

**Issue by mr3y-the-programmer** [cbeyls/HtmlConverterCompose#6]
I've bumped the version of this library from 0.9.5 to 1.0.1 in a project, and when I try to run the project on a device it crashes due to usage of `htmlToAnnotatedString` with some HTML text on the main screen of my app.

I managed to Reproduce the issue which is just as simple as doing this:

```kotlin
Box(
    modifier = Modifier.fillMaxSize()
) {
    val text = "<p>Google TV gets a major update while Xiaomi, Huawei and Nothing are bringing the latest to Android globally. Recorded at Droidcon NYC, Mishaal Rahman, Huyen Tue Dao, Jason Howell and Ron Richards break down the news along with an exclusive interview with Shalini Govil-Pai, VP & GM of Google TV.</p><br><p><em>Note: Time codes subject to change depending on dynamic ad insertion by the distributor.</em></p><br><p>NEWS</p><ul><li>00:06:20 - The numbers are in and <a href=\"https://www.counterpointresearch.com/insights/xiaomi-overtakes-apple-to-become-worlds-no-2-smartphone-brand-in-aug/\" rel=\"noopener noreferrer\" target=\"_blank\">Xiaomi passed Apple as the No. 2</a> smartphone brand in the world</li><li>00:13:20 - Google is making it easier to <a href=\"https://blog.google/technology/safety-security/google-password-manager-passkeys-update-september-2024/\" rel=\"noopener noreferrer\" target=\"_blank\">sync passkeys across devices</a>, but it's still confusing</li><li>00:20:06 - Oppo has a <a href=\"https://www.androidauthority.com/oppo-color-os-15-release-date-3483005/\" rel=\"noopener noreferrer\" target=\"_blank\">launch date for ColorOS 15</a> and <a href=\"https://www.androidauthority.com/oxygen-os-15-ios-features-leak-3482986/\" rel=\"noopener noreferrer\" target=\"_blank\">Oxygen OS 15 is getting more iOS</a> esque</li></ul><p><br></p><p>HARDWARE</p><ul><li>00:26:29 - Leaks of the <a href=\"https://www.thetechoutlook.com/tech-whispers/exclusive-samsung-galaxy-a16-5g-will-be-launching-in-india-at-the-end-of-this-month-design-and-specs-leaked/\" rel=\"noopener noreferrer\" target=\"_blank\">Samsung Galaxy A16 5G</a> are out, along with rumors of 6 years of updates</li><li>00:29:30 - The <a href=\"https://x.com/leijun/status/1836724477343768754?t=IuB5z7kHMdrEs44oJeoOxQ&s=19\" rel=\"noopener noreferrer\" target=\"_blank\">Xiaomi MIX Flip is getting global launch</a>. Revisit <a href=\"https://www.androidfaithful.com/xiaomi-mix-flip-launch/\" rel=\"noopener noreferrer\" target=\"_blank\">Mishaal's coverage of the device</a></li><li>00:32:27 - The HUAWEI Mate XT is coming to global markets after all, and here's when</li></ul><p><br></p><p>APPS</p><ul><li>00:36:55 - Microsoft has <a href=\"https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-app-now-available-on-all-major-platforms/ba-p/4246939\" rel=\"noopener noreferrer\" target=\"_blank\">rolled out a Windows App</a> \uD83E\uDD37</li><li>00:39:23 - Teens now have <a href=\"https://www.androidcentral.com/apps-software/instagram-is-rolling-out-a-restricted-version-of-its-app-for-teens\" rel=\"noopener noreferrer\" target=\"_blank\">a restricted version of Instagram</a></li><li>00:43:53 - Google apps roundup with updates to <a href=\"https://9to5google.com/2024/09/17/google-maps-android-auto-add-stop-button/\" rel=\"noopener noreferrer\" target=\"_blank\">Maps</a>, <a href=\"https://www.androidauthority.com/google-photos-ultra-hdr-editing-option-3482561/\" rel=\"noopener noreferrer\" target=\"_blank\">Photos</a>, <a href=\"https://www.androidauthority.com/google-messages-sending-as-3482422/\" rel=\"noopener noreferrer\" target=\"_blank\">Messages</a></li></ul><p><br></p><p>MORE NEWS</p><ul><li>00:49:47 - The <a href=\"https://www.androidfaithful.com/nothing-ear-open/\" rel=\"noopener noreferrer\" target=\"_blank\">Nothing Ear (open) is here</a>! Nothing's first open-ear audio product</li><li>00:53:48 - PATRON NEWS PICK: Can you believe that <a href=\"https://www.androidpolice.com/no-you-werent-imagining-things-google-photos-search-has-been-broken-lately/\" rel=\"noopener noreferrer\" target=\"_blank\">Google Photos was broken</a> a month?</li><li>00:59:56 - A major <a href=\"https://www.androidfaithful.com/google-tv-updates-sept-2024/\" rel=\"noopener noreferrer\" target=\"_blank\">new batch of features are coming to Google TV</a></li></ul><p><br></p><p>INTERVIEW</p><ul><li>01:04:34 - Interview: We chat with Shalini Govil-Pai, VP & GM of Google TV about the latest updates to the platform</li></ul><br /><hr><p style='color:grey; font-size:0.75em;'> Hosted on Ac\n"
    Text(
         text = remember(text) { htmlToAnnotatedString(text) },
         maxLines = 3
     )
}

```
Running this crashes with the following stack trace:
```
java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at androidx.compose.ui.text.MultiParagraphKt.findParagraphsByRange-Sb-Bc2M(MultiParagraph.kt:973)
	at androidx.compose.ui.text.MultiParagraph.getPathForRange(MultiParagraph.kt:447)
	at androidx.compose.ui.text.TextLayoutResult.getPathForRange(TextLayoutResult.kt:562)
	at androidx.compose.foundation.text.TextLinkScope.textRange$lambda$3(TextLinkScope.kt:97)
	at androidx.compose.foundation.text.TextLinkScope.$r8$lambda$wUliv7MpU312Vdu_yMFwbwK7l9M(Unknown Source:0)
	at androidx.compose.foundation.text.TextLinkScope$$ExternalSyntheticLambda0.measure(D8$$SyntheticClass:0)
	at androidx.compose.foundation.text.BasicTextKt.measureWithTextRangeMeasureConstraints(BasicText.kt:453)
	at androidx.compose.foundation.text.BasicTextKt.access$measureWithTextRangeMeasureConstraints(BasicText.kt:1)
	at androidx.compose.foundation.text.LinksTextMeasurePolicy$measure$1.invoke(BasicText.kt:432)
	at androidx.compose.foundation.text.LinksTextMeasurePolicy$measure$1.invoke(BasicText.kt:431)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:223)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildrenBlock$1.invoke(LayoutNodeLayoutDelegate.kt:429)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildrenBlock$1.invoke(LayoutNodeLayoutDelegate.kt:424)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:503)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:457)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:627)
	at androidx.compose.ui.node.InnerNodeCoordinator.onAfterPlaceAt(InnerNodeCoordinator.kt:182)
	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:169)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:35)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Placeable.kt:618)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place$default(Placeable.kt:246)
	at androidx.compose.foundation.text.modifiers.TextAnnotatedStringNode$measure$1.invoke(TextAnnotatedStringNode.kt:459)
	at androidx.compose.foundation.text.modifiers.TextAnnotatedStringNode$measure$1.invoke(TextAnnotatedStringNode.kt:454)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:223)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.onAfterPlaceAt(LayoutModifierNodeCoordinator.kt:270)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:247)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:35)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:646)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:327)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:648)
```
Even though this sounds like a bug in compose itself from the first look, I suspect that the offending code isn't actually in compose but in this library, Why? 

- because I tried replacing `htmlToAnnotatedString` fun with the recently added `AnnotatedString.fromHtml(text)` API that ships with compose itself and the crash disappeared and the text was rendered with no issues
```kotlin
Text(
    text = remember(text) { AnnotatedString.fromHtml(text) },
    maxLines = 3
)
```
- Also removing `maxLines` parameter from `Text` composable surprisingly fixed the issue too.
```kotlin
Text(
    text = remember(text) { htmlToAnnotatedString(text) }
)
```
- And of course, downgrading the library version back to 0.9.5 also fixed the issue.

**Additional Info**:
Compose version used in my project: 1.7 (2024.10.00 BOM)

**Comment by cbeyls** [comment]
Thank you for the report!

This looks like a bug in the Compose code during measurement of the links, maybe because links don't work well in combination with maxlines.

This library does not output the same formatting as AnnotatedString.fromHtml() so you can't compare the two. For example, this library uses paragraph annotations but fromHtml() does not.

The new version uses LinkAnnotation with Compose 1.7, the previous one uses UrlAnnotation with Compose 1.6, the algorithm is exactly the same but the dependencies have been upgraded.
I'll try to isolate the cause of the issue and see if I can find a workaround.

**Comment by mr3y-the-programmer** [comment]
Thank you for your quick response! I didn't know that `fromHtml` works differently under the hood.

Yes, I know that changes were mostly dependency updates & refactoring to the new `LinkAnnotation` API but I was just surprised to see this regression.

**Comment by mr3y-the-programmer** [comment]
Also, related reports [374115892](https://issuetracker.google.com/issues/374115892), [372390054](https://issuetracker.google.com/issues/372390054) on google issue tracker

**Comment by cbeyls** [comment]
It may be an issue with LinkAnnotation used in paragraphs. Since fromHtml doesn't use paragraphs and the old version of this library doesn't use LinkAnnotation, that would make sense. I'll tell you more after doing proper tests.

**Comment by cbeyls** [comment]
After doing some tests I can confirm that this is a bug in Compose UI that occurs on all platforms when using `LinkAnnotation` inside paragraphs, in combination with **maxLines**.
The deprecated `UrlAnnotation` works in paragraphs, and `LinkAnnotation` works without paragraphs as well.

Paragraphs are used to support **text indentation** (in HTML quotes and nested lists for example). I'm not willing to remove that feature but I can change the behavior to disable paragraphs when the `indentUnit` option is set to **0** so you won't have the issue when using that option in combination with `maxLines` (it doesn't make much sense to display indentation when showing a text snippet anyway).

Note that `AnnotatedString.fromHtml()` currently doesn't support indentation, doesn't display bulleted or numbered lists, supports less HTML tags, uses more CPU and only works on Android.

**Comment by mr3y-the-programmer** [comment]
Thanks for your effort, the workaround proposed to fix the issue looks reasonable to me until we see a fix for the root cause from Compose Team. 
I'm aware that `AnnotatedString.fromHtml()` doesn't have the same feature parity as this library, and it is just meant for very simple HTML texts.

**Comment by cbeyls** [comment]
You can now use the new release **1.0.2** to disable paragraph support when using **maxLines**. Also note that if you want the same number of new lines as `AnnotatedString.fromHtml()`, you should enable compact mode:

```kotlin
Text(
    text = remember(text) {
        htmlToAnnotatedString(
            text,
            compactMode = true,
            style = HtmlStyle(indentUnit = TextUnit.Unspecified)
        )
    },
    maxLines = 3
)
```
